console.log("derecha");
console.log("recojer monton");
console.log("derecha");
console.log("recojer monton");
console.log("derecha");
console.log("recojer monton");
console.log("derecha");
console.log("recojer monton");
console.log("arriba");
console.log("recojer monton");
console.log("arriba");
console.log("recojer monton");
console.log("arriba");
console.log("recojer monton");
console.log("arriba");
console.log("recojer monton");
console.log("arriba");
console.log("recojer monton");
